apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: u325p27h1-go 
  janus-idp.io/tekton: u325p27h1-go
  backstage.io/kubernetes-id: u325p27h1-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u325p27h1-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml