apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u325p27h1-go-gitops
  description: This is GitOps manifest for u325p27h1-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=u325p27h1-go
    backstage.io/kubernetes-id: u325p27h1-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhopp-rhtap-testing/u325p27h1-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u325p27h1-go
