apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u325p27h1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u325p27h1-go 
  name: u325p27h1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u325p27h1-go 
